// Matrix-Sharon showcase data
window.SHARON_DATA_ZH = {
  skills: [
    {
      slug: "sql-safety-gate",
      name: "SQL Safety Gate",
      author: "@chenjie",
      authorRole: "Backend Lead",
      category: "Database",
      version: "1.4.2",
      installs: 23,
      teamSize: 28,
      retention: 0.91,
      stars: 18,
      pushedBy: "leader",
      tags: ["safety", "sql", "prod"],
      summary: "在 Claude Code 执行 DROP/TRUNCATE 等危险 SQL 前强制二次确认，并自动检查 WHERE 子句。",
      bodySteps: [
        "扫描所有由 Claude 生成的 SQL",
        "命中危险模式 → 拦截 + 高亮风险",
        "要求二次确认 + 备份指引",
      ],
      updated: "2 天前",
    },
    {
      slug: "pr-review-checklist",
      name: "PR Review Checklist",
      author: "@sharon",
      authorRole: "Tech Lead",
      category: "Workflow",
      version: "2.0.1",
      installs: 26,
      teamSize: 28,
      retention: 0.96,
      stars: 24,
      pushedBy: "leader",
      tags: ["review", "git", "team"],
      summary: "在每次 PR 创建时自动追加团队 checklist：测试、迁移、回滚、安全。",
      bodySteps: [
        "在 git PR 触发器接入",
        "按代码差异生成 checklist",
        "未勾 → 阻塞合并",
      ],
      updated: "5 小时前",
    },
    {
      slug: "log-analyzer",
      name: "Log Analyzer",
      author: "@viki",
      authorRole: "SRE",
      category: "Observability",
      version: "0.9.0",
      installs: 14,
      teamSize: 28,
      retention: 0.72,
      stars: 9,
      pushedBy: null,
      tags: ["logs", "incident"],
      summary: "粘贴一段日志，Claude 自动定位 ERROR 模式、关联请求链路并给出修复假设。",
      bodySteps: [
        "tail 日志或粘贴文本",
        "聚类 + 关联 trace id",
        "输出可能根因 + 复现命令",
      ],
      updated: "昨天",
    },
    {
      slug: "design-doc-template",
      name: "Design Doc Template",
      author: "@riven",
      authorRole: "Architect",
      category: "Writing",
      version: "1.1.0",
      installs: 19,
      teamSize: 28,
      retention: 0.84,
      stars: 12,
      pushedBy: null,
      tags: ["design", "spec"],
      summary: "团队统一的设计文档骨架：背景、目标、非目标、方案、对比、回滚。",
      bodySteps: [
        "/design 触发",
        "Claude 按团队模板填空",
        "导出到 docs/superpowers/specs",
      ],
      updated: "3 天前",
    },
    {
      slug: "migration-planner",
      name: "Migration Planner",
      author: "@libz",
      authorRole: "DBA",
      category: "Database",
      version: "0.4.1",
      installs: 8,
      teamSize: 28,
      retention: 0.62,
      stars: 6,
      pushedBy: null,
      tags: ["migration", "sql"],
      summary: "把 ORM diff 转成可回滚的 SQL migration 脚本，并生成 dry-run 验证清单。",
      bodySteps: [
        "读取 schema diff",
        "生成正/反向 migration",
        "生成 dry-run 检查表",
      ],
      updated: "上周",
    },
    {
      slug: "incident-commander",
      name: "Incident Commander",
      author: "@chenjie",
      authorRole: "Backend Lead",
      category: "Workflow",
      version: "1.0.0",
      installs: 22,
      teamSize: 28,
      retention: 0.88,
      stars: 17,
      pushedBy: "leader",
      tags: ["incident", "ops"],
      summary: "事故应急指挥：自动建立 war room、写时间线、邀请相关人、生成事后报告。",
      bodySteps: [
        "/incident 启动",
        "开 war room channel + 时间线",
        "结束自动生成 postmortem 草稿",
      ],
      updated: "今天",
    },
  ],

  candidates: [
    {
      id: "cand-1",
      name: "API Mock Generator",
      detectedAt: "刚刚 · scanner 发现",
      path: "~/.claude/skills/local/api-mock-generator",
      summary: "你 12 分钟前在本地写完的 skill。要提交到团队市场吗？",
      lines: 142,
      hasTests: true,
    },
    {
      id: "cand-2",
      name: "Changelog Synth",
      detectedAt: "1 小时前",
      path: "~/.claude/skills/local/changelog-synth",
      summary: "根据 git log 自动生成 CHANGELOG.md 条目，按 conventional commit 归类。",
      lines: 87,
      hasTests: false,
    },
  ],

  pendingApproval: [
    {
      id: "sub-1",
      name: "K8s Pod Inspector",
      author: "@viki",
      authorRole: "SRE",
      submittedAt: "23 分钟前",
      summary: "粘贴 kubectl describe 输出，Claude 解释 pod 异常并给修复命令。",
      diffStats: { added: 218, removed: 0 },
      checks: [
        { label: "lint 通过", ok: true },
        { label: "skill.yaml 合法", ok: true },
        { label: "包含 README", ok: true },
        { label: "未声明网络权限", ok: true },
      ],
    },
    {
      id: "sub-2",
      name: "Slack Notify",
      author: "@newbie",
      authorRole: "Junior Eng",
      submittedAt: "刚刚",
      summary: "把 Claude 的输出发到 Slack 频道。需要 webhook 权限。",
      diffStats: { added: 64, removed: 0 },
      checks: [
        { label: "lint 通过", ok: true },
        { label: "skill.yaml 合法", ok: true },
        { label: "包含 README", ok: false },
        { label: "未声明网络权限", ok: false },
      ],
    },
  ],

  inbox: [
    {
      id: "push-1",
      from: "@sharon (leader)",
      skill: "PR Review Checklist",
      version: "2.0.1",
      pushedAt: "10 分钟前",
      note: "团队规范升级，请所有人安装。卸载会被记录但不会被阻止。",
      status: "pending",
    },
    {
      id: "push-2",
      from: "@sharon (leader)",
      skill: "Incident Commander",
      version: "1.0.0",
      pushedAt: "今天 09:14",
      note: "上线值班建议安装。",
      status: "installed",
    },
  ],

  team: [
    { handle: "@sharon", role: "leader", installed: 6, retention: 1.0 },
    { handle: "@chenjie", role: "member", installed: 5, retention: 0.92 },
    { handle: "@viki", role: "member", installed: 4, retention: 0.88 },
    { handle: "@riven", role: "member", installed: 4, retention: 0.81 },
    { handle: "@libz", role: "member", installed: 3, retention: 0.74 },
    { handle: "@newbie", role: "member", installed: 1, retention: 0.32 },
  ],

  packages: [
    { name: "@sharon/server", desc: "Fastify + SQLite，API + OAuth + bundle 出包", lines: "~4.2k" },
    { name: "@sharon/web", desc: "Astro 站点：浏览 / 候选 / 审批 / 推送 / 收件箱", lines: "~3.6k" },
    { name: "@sharon/cli", desc: "sharon install/uninstall/publish/scan/receive", lines: "~1.8k" },
    { name: "@sharon/scanner", desc: "本地 ~/.claude/skills 扫描器，发现『刚写完的』skill", lines: "~0.6k" },
    { name: "@sharon/compiler", desc: "skill 目录 → bundle.tgz，复用自 TeamBrain", lines: "~1.1k" },
    { name: "@sharon/dispatcher", desc: "leader push 接收端，安装 + ack + 留存信号", lines: "~0.7k" },
    { name: "@sharon/seed", desc: "灌入样例 skill，CI/演示用", lines: "~0.3k" },
  ],

  phases: [
    { id: 1, name: "脚手架", desc: "7 包骨架 + SQLite 10 张表 + CI" },
    { id: 2, name: "GitHub OAuth", desc: "/login/github · 第一个登录者 = leader" },
    { id: 3, name: "浏览", desc: "/v1/skills + Astro 列表 + 详情 + README" },
    { id: 4, name: "提交 / 审批", desc: "候选 → 提交 → leader queue → 不可变版本" },
    { id: 5, name: "一键安装", desc: "sharon:// + CLI fallback + bundle 下载" },
    { id: 6, name: "推送 / 留存", desc: "leader push → inbox → ack/done → 留存视图" },
  ],

  cliCommands: [
    {
      cmd: "sharon scan",
      out: [
        "→ 扫描 ~/.claude/skills/local/",
        "✓ 发现 2 个新 skill：",
        "  · api-mock-generator (12 分钟前修改)",
        "  · changelog-synth (1 小时前修改)",
        "已加入『待我决定』队列。",
      ],
    },
    {
      cmd: "sharon publish ./api-mock-generator",
      out: [
        "→ 打包 api-mock-generator",
        "  · 检查 skill.yaml ✓",
        "  · 收集 README ✓",
        "  · 生成 bundle.tgz (3.2 KB)",
        "→ 上传到 Sharon",
        "✓ 已提交，等待 leader 审批 (id=sub-3)",
      ],
    },
    {
      cmd: "sharon install pr-review-checklist",
      out: [
        "→ 解析最新版本：2.0.1",
        "→ 下载 bundle.tgz (4.7 KB)",
        "→ 校验签名 ✓",
        "→ 写入 ~/.claude/skills/pr-review-checklist/",
        "✓ 已安装。Claude Code 重启后生效。",
      ],
    },
    {
      cmd: "sharon receive",
      out: [
        "→ 监听 leader 推送队列…",
        "✓ 收到推送：Incident Commander v1.0.0",
        "→ 自动安装 + 回写 ack",
        "✓ done。已上报留存信号。",
      ],
    },
  ],
};
